# ArxOne Persistence appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'

os: Visual Studio 2019

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
  provider: NuGet
  api_key:
    secure: cSVY4kxJ2RhSfG2ARk8KI/c0iacT2pg7bhGsxyBbCZ1qQVYSGg5rsPA+Q4fmQ6GQ
  skip_symbols: false

